package com.pathsathi.app.voice
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.speech.*
import android.speech.tts.*
import java.util.Locale
class VoiceEngine(c:Context){private val ctx=c.applicationContext;private var tts:TextToSpeech?=null;private var rec:SpeechRecognizer?=null;private var ready=false;fun init(done:(Boolean)->Unit={}){tts=TextToSpeech(ctx){s->ready=s==TextToSpeech.SUCCESS;if(ready){tts?.setSpeechRate(1f);tts?.setPitch(1f)};done(ready)}};fun setLanguage(h:Boolean):Boolean{val r=tts?.setLanguage(if(h)Locale("hi","IN")else Locale.US)?:TextToSpeech.LANG_NOT_SUPPORTED;return r!=TextToSpeech.LANG_MISSING_DATA&&r!=TextToSpeech.LANG_NOT_SUPPORTED};fun speak(t:String,id:String="sathi_utt"){if(ready)tts?.speak(t,TextToSpeech.QUEUE_FLUSH,null,id)};fun stop(){tts?.stop();rec?.cancel()};fun shutdown(){rec?.destroy();rec=null;tts?.shutdown();tts=null};fun isDeviceRecognitionAvailable()=SpeechRecognizer.isRecognitionAvailable(ctx);fun startListening(h:Boolean,onResult:(String)->Unit,done:()->Unit){if(!isDeviceRecognitionAvailable()){done();return};rec?.destroy();rec=SpeechRecognizer.createSpeechRecognizer(ctx).apply{setRecognitionListener(object:RecognitionListener{override fun onReadyForSpeech(p:Bundle?){};override fun onBeginningOfSpeech(){};override fun onRmsChanged(v:Float){};override fun onBufferReceived(b:ByteArray?){};override fun onEndOfSpeech(){};override fun onError(e:Int){done()};override fun onResults(r:Bundle?){r?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)?.firstOrNull()?.takeIf{it.isNotBlank()}?.let(onResult);done()};override fun onPartialResults(p:Bundle?){};override fun onEvent(t:Int,p:Bundle?){} });startListening(Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply{putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);putExtra(RecognizerIntent.EXTRA_LANGUAGE,if(h)"hi-IN"else"en-US")})}}
}
